@CADSFINANCE_HostAddress = http://localhost:5181

GET {{CADSFINANCE_HostAddress}}/api/DonViTinh/
Accept: application/json

###

@CompanyCode = cads

GET {{CADSFINANCE_HostAddress}}/api/reports/stm-pshh/preview?companyCode={{CompanyCode}}&pageNumber=1&pageSize=20
Accept: application/json

###

GET {{CADSFINANCE_HostAddress}}/api/reports/stm-pshh/layout?companyCode={{CompanyCode}}
Accept: application/xml

###

POST {{CADSFINANCE_HostAddress}}/api/reports/stm-pshh/exports?companyCode={{CompanyCode}}&take=500
Content-Type: application/json

{
  "format": "Pdf"
}

###

@ExportJobId = paste-job-id-here

GET {{CADSFINANCE_HostAddress}}/api/reports/stm-pshh/exports/{{ExportJobId}}
Accept: application/json

###
